\c store_inventory;

INSERT INTO inventory (name, image, description, category, price, in_stock, is_favorite, save_for_later, cart) VALUES 
('Spiderman costume', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676560324/pngwing.com_copy_4_jkxwzn.png', 'Spider-Man: Homecoming film series Marvel Cinematic Universe Spider-Man: Homecoming film series Marvel Studios, spider-man, heroes, textile, fictional Character', 'Pop Culture, Adult', 40.99, '9', true, false, true),
('Pirate Adult Costume', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676476731/pngwing.com_nrcrhe.png', 'Bandana, eye patch, and everything else including a sword', 'Pop Culture, Adult', 50.99, '7', false, false, false),
('Clown Adult Costume', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676477378/pngwing.com_copy_urtb6l.png', 'Rainbow wig, red nose, and oversized shoes', 'Horror, Adult', 30.99, '10', false, false, false),
('Ancient Rome Costume party Gladiator Achilles', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676636998/pngwing.com_16_feed9h.png', 'Ancient Rome Costume party Knight Dress, medival knight, halloween Costume, costume parties, cosplay, Renaissance Faires, and more!','History, Adult', 44.99, '10', false, true, false),
('Jasione Canvas Dress', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676142081/Costumn_59_ycxaeg.png', 'Medieval women canvas dress with laces in front and back. Long, split-layer sleeves with white interior and red and gold exterior.', 'History, Adult', 39.99, '8', true, true, true),
('Star Wars Darth Vader', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676636785/pngwing.com_15_ff9u9i.png', 'Star Wars Darth Vader illustration, Anakin Skywalker Luke Skywalker Darth Maul Palpatine Stormtrooper, Darth Vader, fictional Character costume', 'Pop Culture, Adult', 64.99, '6', false, false, false),
('Star Wars Stormtropper Adult', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676636577/pngwing.com_14_jde9gx.png', 'Star Wars Stormtropper art, Stormtrooper Anakin Skywalker,  protective Gear In Sports, galactic Empire', 'Pop Culture, Adult', 64.99, '4', false, false, false),
('Spider Toddler Costume', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676141247/Costumn_37_hznpn7.png', 'Let this little not-so-creepy spider crawl right into your heart!! 100% polyester bodysuit with arms and hood. Bodysuit is plush terry fabric with printed jersey stomach inset and stuffing for bubble bottom. Bodysuit has printed jersey legs with felt, inches attached to jersey sleeves so t up/out when arms are out. Hood is plush terry fabric with antennae.', 'Animal, Kids', 49.99, '15', false, true, false),
('Superman Costume', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676635152/pngwing.com_10_eysu7g.png', 'The Man of Steel! Modeled after the costume worn in the new blockbuster film Dawn of Justice: Superman vs. Batman. Padded jumpsuit with molded logo, gauntlets and 3D boot tops comes with a red cape. Shoes are not included.', 'Pop Culture, Adult', 59.99, '4', true, true, false),
('Pirate Toddler Costume', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676141943/Costumn_42_xrbhck.png', '"Perfect for the little one at home. Pirate costumes includes One Piece Jumpsuit with white shirt and attached black vest,red/white stripped pants,foam pirate headpiece,sash.Size Infant 0-1 year old,Toddler 1-2 year old', 'Pop Culture, Kids', 38.99, '7', true, true, false),
('Cleopatra Ancient Egypt', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676633483/pngwing.com_3_hwx3gq.png', 'This dress would work perfectly for Halloween, Cleopatra Ancient Egypt Clothing Dress, Egypt, halloween Costume', 'History, Adult', 29.99, '15', false, false, false),
('Clown Toddler Costume', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676633010/pngwing.com_3_s6u1bp.png', 'It is time to make them laugh while wearing this colorful clown costume. Clown Costume includes Colorful jumpsuit with attached collar and hat with pom. Sizes Infant 1-2 & Toddler 2-4.', 'Horror, Kids', 19.99, '3', false, false, false),
('Ancient Rome army Soldier', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676634505/pngwing.com_7_jad839.png', 'Ancient Rome Costume Roman army Soldier Toga, roman soldier, halloween Costume', 'History, Adult', 44.99, '6', false, false, false),
('Harley Quinn', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676634841/pngwing.com_9_tlq4vt.png', 'Harley Quinn from Suicide Squad, Margot Robbie Harley Quinn Joker Suicide Squad Deadshot', 'Pop Culture, Adult', 49.99, '11', false, false, false),
('Batman Adult Costume', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676635940/pngwing.com_12_a8odty.png', 'Batman Thomas Wayne Batsuit Comics, justice league', 'Pop Culture, Adult', 59.99, '10', false, false, false),
('Pirate Costume Adult', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676634632/pngwing.com_8_lm1vwy.png', 'Set sail on the hunt for treats and treasures with this Precious adult Costume.', 'Pop Culture, Adult', 29.99, '14', false, false, false),
('Vampire Gothic fashion', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676634306/pngwing.com_6_w4vluh.png', 'Costume Vampire Gothic fashion Clothing Dress-up, neck bloodstain, halloween Costume', 'Horror, Adult', 24.99, '13', false, false, false),
('Skeleton Jumpsuit Adult Costume', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676141703/Costumn_18_lvuiwo.png', 'Skeleton costume includes Black and white bone printed nylon jumpsuit with black hood. Makeup and prop not included.', 'Horror, Adult', 24.99, '9', false, true, false),
('Superman Toddler Costume', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676635642/pngwing.com_11_rohpnn.png', 'Costume party Dress Child Boy, superman', 'Adult, Chrismas', 19.99, '9', false, false, false),
('T-Rex Child Costume', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676141244/Costumn_34_usxsbl.png', 'You will be the king of the jungle when you wear this T-Rex Inflatable Child Costume! This officially licensed Jurassic Park product is made of lightweight polyester and features realistic', 'Animal, Kids', 24.99, '5', true, false, true),
('Hulk Child Qualux Costume', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676141254/Costumn_36_dzetvi.png', 'Get pumped and ready for thrilling action dressed as Marvels Hulk . The high quality Qualux outfit come straight from the designs seen in Marvel, and includes everything you need to transform yourself. If your Costume ever gets stained be sure to Hand wash with cold water by hand. The Green, Printed Padded Polyester Marvel Costume from the Marvel Universe is just what you need to showcase your own unique style!', 'Pop Culture, Kids', 24.99, '4', false, false, false),
('Batman Kids Costume - The Dark Knight Rises', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676141223/Costumn_31_kcw8sb.png', 'Headpiece jumpsuit and cape. Toddler size fits 2T to 4T. Costume is from the Dark Knight Series', 'Pop Culture, Kids', 34.99, '5', false, false, false),
('Penguin Costume Toddler', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676141257/Costumn_41_r4566h.png', 'Dress up your little one up in this tuxedo wearing bird pufit and watch them waddle their way through the neighborhood this Halloween! Warm and cozy, this toddler animal suit is perfect for cold Halloween nights! The Penguin Toddler costume includes a black and white plush body, penguin headpiece and a pair of orange shoe covers that look like webbed feet. The headpiece fastens under the chin.', 'Animal, Kids', 34.99, '5', false, false, false),
('Girls Wicked Witch Of The West', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676633735/pngwing.com_4_kwdkzk.png', 'Inspired by the classic movie The Wizard of Oz comes this great costume based on the Wicked Witch of the West. Black and orange and purple dress with black witch hat.', 'Horror, Kids', 24.99, '5', false, false, false),
('Wicked Witch Adult', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676634075/pngwing.com_5_vyqs5q.png', 'Wicked Witch of the West The Wizard of Oz Costume party Includes all black Dress, vest, broom and hat. Sizes Extra Small 0-2, Small 2-6 & Medium 6-10.', 'Horror, Adult', 24.99, '5', false, false, false),
('Ghost Costume', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676478413/pngwing.com_copy_4_tjg44o.png', 'White sheet with cut-out eyes. Robe Halloween costume Ghost.', 'Horror, Adult', 15.99, '7', false, false, false),
('Skeleton Adult Costume', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676477591/pngwing.com_copy_4_tvttfc.png', 'Black jumpsuit and green skeletal makeup for adult', 'Horror, Adult', 25.99, '4', false, false, false),
('Black Panther Head Costume', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676478789/pngwing.com_copy_5_cscd1h.png', 'Black Panther Costume Cosplay Mask Clothing, black panther, fictional Characters', 'Pop Culture, Adult', 45.00, '11', false, false, false),
('Ninja Costume', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676477791/pngwing.com_copy_gkhn4n.png', 'Black clothing and ninja accessories, Halloween costume Ninja Suit Clothing adult', 'Pop Culture, Adult', 35.99, '3', true, true, false),
('Black Panther full costume', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676481392/pngwing.com_copy_p3mv8y.png', 'Black Panther full costume, Avengers role, fictional Character', 'Pop Culture, Adult', 54.99, '9', true, true, false);


INSERT INTO reviews (item_id, reviewer, title, content, rating )
VALUES
('1', 'Evan', 'My Favorite', 'This costume is so cool!', 4),
('5', 'Eva', 'My honest opinion', 'This is not the most comfortable, but it is still very beautifull. I wish the material was a bit more comfortable', 3),
('3', 'John', 'My Least Favorite', 'This costume is awesome, but it was the wrong size for me', 1),
('5', 'Juliana', 'I Love this', 'I finally have something to wear for my acting practice. It is beautifull and the perfect size.', 5),
('13', 'David', 'Cool costume', 'This is all I need for Halloween!', 4),
('18', 'Mr. Mingo', 'So scary', 'The perfect Halloween costume to scary the trick-or-treaters away! I love it', 5),
('17', 'Alison', 'So comfortable','I love this costume because it keeps me warm', 5),
('29', 'Hannah', 'Insert Confetti Emoji Here', 'I love this costume just like I love Martial Arts!', 4),
('22', 'Gabi', 'I am Batman', 'My son thinks he is Batman now. hAhahah!', 5);
