\c store_inventory;

INSERT INTO inventory (name, image, description, category, price, in_stock, is_favorite, save_for_later, cart) VALUES 
('Spiderman costume', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676560324/pngwing.com_copy_4_jkxwzn.png', 'Spider-Man: Homecoming film series Marvel Cinematic Universe Spider-Man: Homecoming film series Marvel Studios, spider-man, heroes, textile, fictional Character', 'Pop Culture, Adult', 40.00, '9', true, false, true),
('Pirate Adult Costume', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676476731/pngwing.com_nrcrhe.png', 'Bandana, eye patch, and everything else including a sword', 'Classic, Adult', 50.00, '7', false, false, false),
('Clown Adult Costume', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676477378/pngwing.com_copy_urtb6l.png', 'Rainbow wig, red nose, and oversized shoes', 'Horror, Adult', 30.00, '10', false, false, false),
('Deluxe Renaissance Adult Pant Costume', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676142085/Costumn_56_rke4fd.png', 'This historical costume is modeled after the English monarch royal garb. The Deluxe Henry VIII Adult Costume is ideal for Halloween, costume parties, cosplay, Renaissance Faires, and more!','Medieval, Adult', 14.99, '10', false, true, false),
('Jasione Canvas Dress', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676142081/Costumn_59_ycxaeg.png', 'Medieval women canvas dress with laces in front and back. Long, split-layer sleeves with white interior and red and gold exterior.', 'Medieval, Adult', 39.99, '8', true, true, true),
('Superman Grand Heritage Costume Kids', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676141712/Costumn_45_jxxmmx.png', ' The Man of Steel! Modeled after the costume worn in the new blockbuster film Dawn of Justice: Superman vs. Batman. Padded jumpsuit with molded logo, gauntlets and 3D boot tops comes with a red cape. Shoes are not included.', 'Pop Culture, Kids', 34.99, '6', false, false, false),
('Horse Head Costume Adult', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676141700/Costumn_17_veygep.png', 'Comfortable to wear for all head size. ade with Silicon and care. Wear this and a horse will mistake you for a horse', 'Animal, Adult', 64.99, '4', false, false, false),
('Spider Toddler Costume', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676141247/Costumn_37_hznpn7.png', 'Let this little not-so-creepy spider crawl right into your heart!! 100% polyester bodysuit with arms and hood. Bodysuit is plush terry fabric with printed jersey stomach inset and stuffing for bubble bottom. Bodysuit has printed jersey legs with felt, inches attached to jersey sleeves so t up/out when arms are out. Hood is plush terry fabric with antennae.
', 'Animal, Kids', 49.99, '15', false, true, false),
('Pirate Infant/Toddler Costume', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676141943/Costumn_42_xrbhck.png', '"Perfect for the little one at home. Pirate costumes includes One Piece Jumpsuit with white shirt and attached black vest,red/white stripped pants,foam pirate headpiece,sash.Size Infant 0-1 year old,Toddler 1-2 year old', 'Pop Culture, Kids', 38.99, '7', true, true, false),
('Woman Theatrical Head Costume', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676142092/Costumn_58_sjohun.png', 'This head dress would work perfectly for Halloween, cultural event, and theatrical productions', 'Theatre, Kids', 29.99, '15', false, false, false),
('Clown Infant/Toddler Costume', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676141251/Costumn_33_nh6lr1.png', 'It is time to make them laugh while wearing this colorful clown costume. Clown Costume includes Colorful jumpsuit with attached collar and hat with pom. Sizes Infant 1-2 & Toddler 2-4.', 'Horror, Kids', 19.99, '3', false, false, false),
('Albert Beaver Mascot', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676142079/Costumn_65_w6zmyq.png', 'Albert Beaver Mascot. This Albert Beaver mascot comes complete with head, body, hand mitts and foot covers.Comfortable to wear and easy to maintain.', 'Animal, Adult', 44.99, '6', false, false, false),
('Ringmaster Costume Adult Mens', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676142076/Costumn_68_iaacha.png', 'Tail coat with chain closure, vest dickey with attached bow tie, top hat and boot covers. Simply supply your own pants.', 'Theatre, Adult', 49.99, '11', false, false, false),
('Scary Clown Adult Costume', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676141931/Costumn_48_bisxps.png', 'There is always been a sort of uneasiness between people and clowns. Possibly because no one knows quite what is behind the greasepaint. Anyone who sees you in this costume will get that same sort of uneasiness and trepidation, if not outright fear! Jumpsuit with blue with stars on one side and white with red vertical stripes on the other, matching collar and mask.', 'Horror, Adult', 19.99, '10', false, false, false),
('Pirate Face Costume Adult', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676141693/Costumn_13_septce.png', 'Set sail on the hunt for treats and treasures with this Precious adult Costume.', 'Pop Culture, Adult', 9.99, '14', false, false, false),
('Scary Devil Mask', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676141928/Costumn_25_yd9phu.png', 'A scary devil mask in red and black', 'Horror, Adult', 14.99, '13', false, false, false),
('Skeleton Jumpsuit Adult Costume', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676141703/Costumn_18_lvuiwo.png', 'Skeleton costume includes Black and white bone printed nylon jumpsuit with black hood. Makeup and prop not included.', 'Horror, Adult', 24.99, '9', false, true, false),
('Womean Elf Costume', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676142088/Costumn_62_owyj2n.png', ' Instantly become a huge hit with your holiday Costumes this year. Elf. Costume includes jacket, tights, belt and hat with feather. Available in Adult Sizes Standard or Extra Large.', 'Adult, Chrismas', 19.99, '9', false, false, false),
('T-Rex Child Costume', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676141244/Costumn_34_usxsbl.png', 'You will be the king of the jungle when you wear this T-Rex Inflatable Child Costume! This officially licensed Jurassic Park product is made of lightweight polyester and features realistic', 'Animal, Kids', 24.99, '5', true, false, true),
('Hulk Child Qualux Costume', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676141254/Costumn_36_dzetvi.png', 'Get pumped and ready for thrilling action dressed as Marvels Hulk . The high quality Qualux outfit come straight from the designs seen in Marvel, and includes everything you need to transform yourself. If your Costume ever gets stained be sure to Hand wash with cold water by hand. The Green, Printed Padded Polyester Marvel Costume from the Marvel Universe is just what you need to showcase your own unique style!', 'Pop Culture, Kids', 24.99, '4', false, false, false),
('Batman Kids Costume - The Dark Knight Rises', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676141223/Costumn_31_kcw8sb.png', 'Headpiece jumpsuit and cape. Toddler size fits 2T to 4T. Costume is from the Dark Knight Series', 'Pop Culture, Kids', 34.99, '5', false, false, false),
('Penguin Costume Toddler', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676141257/Costumn_41_r4566h.png', 'Dress up your little one up in this tuxedo wearing bird pufit and watch them waddle their way through the neighborhood this Halloween! Warm and cozy, this toddler animal suit is perfect for cold Halloween nights! The Penguin Toddler costume includes a black and white plush body, penguin headpiece and a pair of orange shoe covers that look like webbed feet. The headpiece fastens under the chin.', 'Animal, Kids', 34.99, '5', false, false, false),
('Girls Wicked Witch Of The West Costume', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676141237/Costumn_27_dxhncf.png', 'From the movie classic The Wizard of Oz comes this great costume based on the Wicked Witch of the West. Black and gold dress with green collar and accents including design on bottom of skirt green cape and black witch hat.', 'Horror, Kids', 24.99, '5', false, false, false),
('Wicked Witch Adult Costume Medium', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676141676/Costumn_20_fwhpqe.png', 'Wicked Witch Adult Costume Includes Dress, cape,and hat. Sizes Extra Small 0-2, Small 2-6 & Medium 6-10.', 'Horror, Adult', 24.99, '5', false, false, false),
('Ghost', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676478413/pngwing.com_copy_4_tjg44o.png', 'White sheet with cut-out eyes. Robe Halloween costume Ghost.', 'Horror, Adult', 15.00, '7', false, false, false),
('Skeleton Adult Costume', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676477591/pngwing.com_copy_4_tvttfc.png', 'Black jumpsuit and green skeletal makeup for adult', 'Horror, Adult', 25.00, '4', false, false, false),
('Black Panther Head Costume', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676478789/pngwing.com_copy_5_cscd1h.png', 'Black Panther Costume Cosplay Mask Clothing, black panther, fictional Characters', 'Pop Culture, Adult', 45.00, '11', false, false, false),
('Ninja', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676477791/pngwing.com_copy_gkhn4n.png', 'Black clothing and ninja accessories, Halloween costume Ninja Suit Clothing adult', 'Pop Culture, Adult', 35.00, '3', true, true, false),
('Black Panther full costume', 'https://res.cloudinary.com/dht9k25qd/image/upload/v1676481392/pngwing.com_copy_p3mv8y.png', 'Black Panther full costume, Avengers role, fictional Character', 'Pop Culture, Adult', 54.99, '9', true, true, false);


INSERT INTO reviews (item_id, reviewer, title, content, rating )
VALUES
('1', 'Evan', 'My Favorite', 'This costume is so cool!', 4),
('5', 'Eva', 'My honest opinion', 'This not the most comfortable, but it is still very beautifull. I wish the material was a bit more comfortable', 3),
('3', 'John', 'My Least Favorite', 'This costume is awesome, but it was the wrong size for me', 1),
('5', 'Juliana', 'I Love this', 'I finally have something to wear for my acting practice. It is beautifull and the perfect size.', 5),
('12', 'David', 'Cool costume', 'This is all I need for Halloween!', 4),
('14', 'Mr. Mingo', 'So scary', 'The perfect Halloween costume to scary the trick-or-treaters away! I love it', 5),
('19', 'Alison', 'So comfortable','I love this costume because it keeps me warm', 5),
('4', 'Hannah', 'Insert Confetti Emoji Here', 'The description is so true, hahahah. My horse thought I was a horse!', 4),
('3', 'Gabi', 'I am Batman', 'My son thinks he is Batman now. hAhahah!', 5);
